---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### Load Libraries
```{r}
library(GenSA)
library(ggplot2)
library(GA)

```
```{r}
#Load Libraries
install.packages('GA')

library('ggplot2')
library('quantmod')
library('GA')
library('GenSA')
library('PerformanceAnalytics')

```

```{r}
#Feeding real-time stock data into the system
tickers <- c("GM", "AMZN", "BMWYY", "LVMUY", "KO")
getSymbols(tickers, from = "2010-12-01", to = "2018-11-05")
P <- NULL
for(ticker in tickers) {
  tmp <- Cl(to.monthly(eval(parse(text = ticker))))
  P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
  fn.call <<- fn.call + 1
  if (sum(w) == 0) { w <- w + 1e-2 }
  w <- w / sum(w)
  CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
  tmp1 <- CVaR$ES
  tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
  out <- tmp1 - 1e+3 * tmp2
  return(out)
}
obj1 <- function(w) {
  fn.call <<- fn.call + 1
  if (sum(w) == 0) { w <- w + 1e-2 }
  w <- w / sum(w)
  CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
  tmp1 <- CVaR$ES
  tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
  out1 <- tmp1 + 1e+3 * tmp2
  return(out1)
}
```

```{r}

# Solution is the weights assigned to each of the stocks for optimum portfolio
set.seed(1234)
fn.call <<- 0
gap <- ga(type = "real-valued",fitness=obj,lower=rep(0,5),upper=rep(1,5), popSize = 50,maxiter = 150, pcrossover = 0.75, pmutation = 0.1)
nsol <- gap@solution
nsol <- nsol / sum(nsol)
fn.call.gap <- fn.call
nsol
summary(gap)
plot(gap)
```

```{r}
#Applying GenSA to assign weights to the stocks for optimum portfolio using max objective
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj1, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
wstar.GenSA
```

```{r}
#comparing the weights as per both the algorithms
b <- matrix(c(nsol, wstar.GenSA), nrow = 5, ncol = 2)
rownames(b) = c("GM", "AMZN", "BMWYY", "LVMUY", "KO")
colnames(b) = c("GAPortfolio", "GenSAPortfolio")
b
TickerSymbol <- (c("GM", "AMZN", "BMWYY", "LVMUY", "KO","______________","TOTAL"))
Company <- (c("General Motors","Amazon","BMW","Louis Vuitton","Coca-Cola","______________",""))
GA_percent  <- (c(17,22,14,18,29,"______________ ",100))
GenSA_percent <- (c(16,20,6,16,42,"______________ ",100))
TData <- data.frame(TickerSymbol, Company, GA_percent, GenSA_percent) 
TData
```
```{r}
#Question number 2
x <- c(1, 3, 7, 9, 5, 2, 4, 8, 6, 22, 11, 33)
y <- c(50, 60, 70, 80, 90, 100, 66, 18, 32, 28, 69, 44)

a <- sum((y - mean(y)) ^ 2)
a1 <- sum((x - mean(x)) * (y - mean(y)))
a2 <- sum((x - mean(x)) ^ 2)
b1 <- a1/a2
b0 <- mean(y) - b1 * mean(x)

print(b1)
print(b0)
```

```{r}
linear_model <- lm(y ~ x)

summary(linear_model)
```

```{r}
obj <- function (r) {
    fn <- function (b0, b1) {
        return (sum(y - (b0 + b1 * x)) ^ 2)
    }
    return (fn(r[1], r[2]))
}

ubound <- c(2, 1)
lbound <- c(0, 0)
```


```{r}
#GA
ga_search <- ga(
    type = "real-valued",
    fitness = function (x) -obj(x),
    lower = lbound,
    upper = ubound,
    popSize = 50
)
summary(ga_search)
plot(ga_search)
```
```{r}
#SA
par <- c(1, 0)

sa_search <- GenSA(
    par = par,
    lower = lbound,
    upper = ubound,
    fn = obj
)
```








